#################################################################
#                                                               #
#                       configuration.yaml                      #
#                                                               #
################################################################# 
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

# Enables the frontend
#frontend:

lovelace:
  mode: yaml

# Enables the System Health component
system_health:

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  api_password: TestTest

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyACM0
  debug: true
  
rfxtrx:
  device: /dev/ttyUSB0

tibber:
  access_token: !secret tibber_access_token

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
    
input_select:
  system_mode:
    name: System Mode
    options:
     - HOME
     - NIGHT
     - AWAY
     - VACATION
    icon: mdi:panda
    
group: !include groups.yaml
automation: !include automations.yaml
climate: !include climate.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
