#################################################################
#                                                               #
#                       configuration.yaml                      #
#                                                               #
################################################################# 
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:
  themes: !include_dir_named themes
  
custom_updater:
  track:
    - cards
    - components
# show_installable: true
  card_urls:
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json

lovelace:
  mode: yaml

# Enables the System Health component
system_health:

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt:
  broker: 192.168.2.140
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password

zwave:
  usb_path: /dev/ttyACM0
  debug: true
  
rfxtrx:
  device: /dev/ttyUSB0

tibber:
  access_token: !secret tibber_access_token

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
    
input_select:
  system_mode:
    name: System Mode
    options:
     - HOME
     - NIGHT
     - AWAY
     - VACATION
    icon: mdi:panda
    
cover:
  - platform: mqtt
    name: "garage_door"
    state_topic: "home/outside/garage/door/state"
    command_topic: "home/outside/garage/door/set"
    availability_topic: "home/outside/garage/door/availability"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "open"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    retain: false

#################################################################
#                                                               #
#                           INCLUDES                            #
#                                                               #
################################################################# 
automation: !include automation.yaml
climate: !include climate.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
sensor: !include sensors.yaml

