title: Home Automation
resources:
  - url: /customcards/custom-lovelace/bignumber-card.js
    type: js
  - url: /customcards/custom-lovelace/button-card.js
    type: module
  - url: /customcards/custom-lovelace/tracker-card.js?track=true
    type: module
  - url: /customcards/custom-lovelace/vertical-stack-in-card.js
    type: js
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js    

views:
# Main View
  - icon: mdi:home #Icon
    title: Hjem #Tool Tip
    path: home
    cards:
      # First Card on the 'Main' View
      - type: entities
        entities:
          - type: gauge0
            entity: sensor.real_time_consumption_herman_grans_vei_58_a
            name: Effektforbruk
            min: 0
            max: 10000
            unit: W
            severity:
              green: 0
              yellow: 4000
              red: 8000
          - type: input_boolean
            entity: input_boolean.kitchen_heating_enable
          - type: input_boolean
            entity: input_boolean.livingroom_heating_enable
          - type: input_boolean
            entity: input_boolean.hugosroom_heating_enable
          - type: input_select
            entity: input_select.system_mode
          - type: cover
            entity: cover.garage_door
      - type: custom:tracker-card

# Temperatures View
  - icon: mdi:thermometer #Icon
    title: Temperaturer
    path: temperatures
    cards:
      - type: entities
        title: Temperaturer
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: input_number.kitchen_temperature_setpoint
            name: Kjøkken
          - type: custom:slider-entity-row
            entity: input_number.livingroom_temperature_setpoint
            name: Stue
          - type: custom:slider-entity-row
            entity: input_number.hugosroom_temperature_setpoint
            name: Hugos rom

# Tablet View
  - icon: mdi:tablet-cellphone
    title: Dashboard
    path: dashboard
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: custom:vertical-stack-in-card
            title: Kjøkken
            cards: 
            - type: "horizontal-stack"
              cards:
              - type: "custom:bignumber-card"
                entity: input_number.kitchen_temperature_setpoint
                scale: 23px
                from: left
                min: 16
                max: 30
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:thermometer-minus
                tap_action:
                  action: call-service
                  service: input_number.decrement
                  service_data:
                    entity_id: input_number.kitchen_temperature_setpoint
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:thermometer-plus
                tap_action:
                  action: call-service
                  service: input_number.increment
                  service_data:
                    entity_id: input_number.kitchen_temperature_setpoint
              - type: "custom:button-card"
                entity: input_boolean.kitchen_heating_enable
                state:
                  - value: 'off'
                    icon: mdi:radiator-off
                  - value: 'on'
                    icon: mdi:radiator
            
          - type: custom:vertical-stack-in-card
            title: Stue
            cards:        
            - type: "horizontal-stack"
              cards:
              - type: "custom:bignumber-card"
                entity: input_number.livingroom_temperature_setpoint
                scale: 23px
                from: left
                min: 16
                max: 30
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:thermometer-minus
                tap_action:
                  action: call-service
                  service: input_number.decrement
                  service_data:
                    entity_id: input_number.livingroom_temperature_setpoint
              - type: "custom:button-card"
                color_type: card
                color: rgb(223, 255, 97)
                icon: mdi:thermometer-plus
                tap_action:
                  action: call-service
                  service: input_number.increment
                  service_data:
                    entity_id: input_number.livingroom_temperature_setpoint
              - type: "custom:button-card"
                entity: input_boolean.livingroom_heating_enable
                state:
                  - value: 'off'
                    icon: mdi:radiator-off
                  - value: 'on'
                    icon: mdi:radiator

