title: Home Automation
resources:
  - url: /local/plugins/slider-entity-row.js?v=1
    type: js
    
views:
# Main View
  - icon: mdi:home #Icon
    title: Hjem #Tool Tip
    id: Main # Optional unique id for direct access /lovelace/${id}
    cards:
      # First Card on the 'Main' View
      - type: entities
        entities:
          - type: gauge
            entity: sensor.real_time_consumption_herman_grans_vei_58_a
            name: Effektforbruk
            min: 0
            max: 10000
            unit: W
            severity:
              green: 0
              yellow: 4000
              red: 8000
          - type: input_boolean
            entity: input_boolean.kitchen_heating_enable
          - type: input_boolean
            entity: input_boolean.livingroom_heating_enable
          - type: input_boolean
            entity: input_boolean.hugosroom_heating_enable
          - type: input_select
            entity: input_select.system_mode
          - type: cover
            entity: cover.garage_door

# Temperatures View
  - icon: mdi:thermometer #Icon
    title: Temperaturer
    id: Temperatures
    cards:
      - type: entities
        title: Temperaturer
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: input_number.kitchen_temperature_setpoint
            name: Kjøkken
          - type: custom:slider-entity-row
            entity: input_number.livingroom_temperature_setpoint
            name: Stue
          - type: custom:slider-entity-row
            entity: input_number.hugosroom_temperature_setpoint
            name: Hugos rom

